import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { addTask } from "@/store/tasks";
import { addRecurringTask } from "@/store/tasks";
import { useAppDispatch } from "@/store/hooks";
import { expandRecurrence, presetToRRule, type RecurrencePreset } from "@/data/recurrence";
import { pickAndPersistImages } from "@/services/media/imageService";
import { AudioRecorderPanel } from "@/components/AudioRecorderPanel";

const pad = (value: number) => String(value).padStart(2, "0");
export default function NewTask() {
  const { kind = "normal" } = useLocalSearchParams<{ kind?: "normal" | "leave" }>(); const dispatch = useAppDispatch();
  const [content, setContent] = useState(""); const [studentName, setStudentName] = useState(""); const [images, setImages] = useState<string[]>([]); const [recordings, setRecordings] = useState<string[]>([]); const [dateText, setDateText] = useState(() => { const date = new Date(); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`; }); const [timeText, setTimeText] = useState("09:00"); const [leavePeriod, setLeavePeriod] = useState<0 | 1 | 2>(0); const [recurrence, setRecurrence] = useState<RecurrencePreset>("none"); const [untilText, setUntilText] = useState(() => { const date = new Date(); date.setMonth(date.getMonth() + 3); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`; });
  async function save() { if (!content.trim()) { Alert.alert("请填写事务内容"); return; } if (kind === "leave" && !studentName.trim()) { Alert.alert("请填写学生姓名"); return; } const date = new Date(`${dateText}T${timeText}:00`); if (Number.isNaN(date.getTime())) { Alert.alert("日期或时间格式不正确"); return; } const input = { kind, content: content.trim(), eventAt: date.getTime(), eventDate: dateText, notifyEnabled: true, remindAt: date.getTime(), completionSupported: true, studentName: kind === "leave" ? studentName.trim() : null, leaveDate: kind === "leave" ? dateText : null, leavePeriod: kind === "leave" ? leavePeriod : null, recurrenceRule: presetToRRule(recurrence), recurrenceGroupId: null, images, recordings } as const; if (recurrence === "none") await dispatch(addTask(input)); else { const until = new Date(`${untilText}T23:59:59`).getTime(); if (until < date.getTime()) { Alert.alert("循环结束日期不能早于开始日期"); return; } await dispatch(addRecurringTask(input, until)); } router.back(); }
  async function pickImages() { const selected = await pickAndPersistImages(Math.max(0, 5 - images.length)); setImages((current) => [...current, ...selected]); }
  function previewCount() { const start = new Date(`${dateText}T${timeText}:00`).getTime(); const until = new Date(`${untilText}T23:59:59`).getTime(); if (recurrence === "none" || Number.isNaN(start) || Number.isNaN(until)) return 1; return expandRecurrence({ preset: recurrence, startAt: start, until }).length; }
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.cancel}>取消</Text></Pressable><Text style={styles.headerTitle}>{kind === "leave" ? "学生请假" : "新建日程"}</Text><Pressable onPress={save}><Text style={styles.save}>保存</Text></Pressable></View><Text style={styles.label}>事项内容</Text><TextInput value={content} onChangeText={setContent} placeholder={kind === "leave" ? "例如：数学课请假" : "例如：收集家长回执"} style={styles.input} />{kind === "leave" && <><Text style={styles.label}>学生姓名</Text><TextInput value={studentName} onChangeText={setStudentName} placeholder="请输入学生姓名" style={styles.input} /><Text style={styles.label}>请假时段</Text><View style={styles.segment}>{([0, 1, 2] as const).map((item) => <Pressable key={item} onPress={() => setLeavePeriod(item)} style={[styles.segmentItem, leavePeriod === item && styles.segmentActive]}><Text style={leavePeriod === item ? styles.segmentTextActive : styles.segmentText}>{item === 0 ? "全天" : item === 1 ? "上午" : "下午"}</Text></Pressable>)}</View></>}<Text style={styles.label}>日期</Text><TextInput value={dateText} onChangeText={setDateText} placeholder="YYYY-MM-DD" style={styles.input} keyboardType="numbers-and-punctuation" /><Text style={styles.label}>提醒时间</Text><TextInput value={timeText} onChangeText={setTimeText} placeholder="HH:mm" style={styles.input} keyboardType="numbers-and-punctuation" /><Text style={styles.label}>循环日程</Text><View style={styles.segment}>{(["none", "daily", "weekly", "monthly", "monthEnd"] as const).map((item) => <Pressable key={item} onPress={() => setRecurrence(item)} style={[styles.segmentItem, recurrence === item && styles.segmentActive]}><Text style={recurrence === item ? styles.segmentTextActive : styles.segmentText}>{item === "none" ? "不循环" : item === "daily" ? "每天" : item === "weekly" ? "每周" : item === "monthly" ? "每月" : "月底"}</Text></Pressable>)}</View>{recurrence !== "none" && <><Text style={styles.label}>循环结束日期</Text><TextInput value={untilText} onChangeText={setUntilText} placeholder="YYYY-MM-DD" style={styles.input} keyboardType="numbers-and-punctuation" /><Text style={styles.preview}>将生成约 {previewCount()} 条日程</Text></>}<Text style={styles.label}>图片和录音</Text><View style={styles.mediaRow}><Pressable onPress={pickImages} style={styles.mediaButton}><Text style={styles.mediaText}>＋ 添加图片 ({images.length})</Text></Pressable><AudioRecorderPanel onSaved={(uri) => setRecordings((current) => [...current, uri])} /></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#fffdf8" }, container: { padding: 20, paddingBottom: 40 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 26 }, headerTitle: { color: "#263c36", fontSize: 18, fontWeight: "700" }, cancel: { color: "#8ca198", fontSize: 16 }, save: { color: "#43a286", fontSize: 16, fontWeight: "700" }, label: { color: "#536960", fontSize: 14, marginTop: 14, marginBottom: 8 }, input: { backgroundColor: "#f2f7f3", borderRadius: 14, padding: 14, color: "#263c36", fontSize: 16 }, segment: { flexDirection: "row", gap: 8 }, segmentItem: { flex: 1, padding: 13, alignItems: "center", backgroundColor: "#f2f7f3", borderRadius: 12 }, segmentActive: { backgroundColor: "#bfe5d6" }, segmentText: { color: "#789087" }, segmentTextActive: { color: "#267b63", fontWeight: "700" }, preview: { color: "#4aa488", marginTop: 8 }, mediaRow: { gap: 12 }, mediaButton: { padding: 14, backgroundColor: "#edf6f1", borderRadius: 14 }, mediaText: { color: "#4aa488" } });
