import { router, useFocusEffect } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { TaskCard } from "@/components/TaskCard";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { editTask, loadTasks } from "@/store/tasks";

type Range = "week" | "month" | "year" | "custom";
export default function Search() {
  const dispatch = useAppDispatch(); const tasks = useAppSelector((state) => state.tasks.items); const [keyword, setKeyword] = useState(""); const [range, setRange] = useState<Range>("week"); const [fromText, setFromText] = useState(""); const [toText, setToText] = useState("");
  useFocusEffect(useCallback(() => { void dispatch(loadTasks({ keyword })); }, [dispatch, keyword]));
  useEffect(() => { const timer = setTimeout(() => { const now = new Date(); const from = new Date(now); from.setHours(0, 0, 0, 0); const to = new Date(from); if (range === "week") { const day = from.getDay() || 7; from.setDate(from.getDate() - day + 1); to.setTime(from.getTime()); to.setDate(to.getDate() + 7); } else if (range === "month") { from.setDate(1); to.setMonth(to.getMonth() + 1, 1); } else if (range === "year") { from.setMonth(0, 1); to.setFullYear(to.getFullYear() + 1, 0, 1); } else { const customFrom = new Date(`${fromText}T00:00:00`); const customTo = new Date(`${toText}T23:59:59`); if (Number.isNaN(customFrom.getTime()) || Number.isNaN(customTo.getTime())) return; from.setTime(customFrom.getTime()); to.setTime(customTo.getTime()); } void dispatch(loadTasks({ keyword, from: from.getTime(), to: to.getTime() })); }, 300); return () => clearTimeout(timer); }, [dispatch, keyword, range, fromText, toText]);
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ 返回</Text></Pressable><Text style={styles.title}>所有日程</Text><View style={{ width: 45 }} /></View><View style={styles.search}><TextInput value={keyword} onChangeText={setKeyword} placeholder="搜索事务内容" placeholderTextColor="#9aac9f" style={styles.input} /><View style={styles.filters}>{(["week", "month", "year", "custom"] as const).map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.filter, range === item && styles.filterActive]}><Text style={range === item ? styles.filterTextActive : styles.filterText}>{item === "week" ? "本周" : item === "month" ? "本月" : item === "year" ? "本年" : "自定义"}</Text></Pressable>)}</View>{range === "custom" && <View style={styles.custom}><TextInput value={fromText} onChangeText={setFromText} placeholder="开始 YYYY-MM-DD" style={styles.customInput} /><TextInput value={toText} onChangeText={setToText} placeholder="结束 YYYY-MM-DD" style={styles.customInput} /></View>}</View><ScrollView contentContainerStyle={styles.scroll}>{tasks.length ? tasks.map((task) => <TaskCard key={task.id} task={task} onPress={() => router.push(`/task/${task.id}` as never)} onComplete={() => void dispatch(editTask(task.id, { completed: true, completedAt: Date.now() }))} />) : <Text style={styles.empty}>没有找到相关日程</Text>}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#fffdf8" }, header: { padding: 20, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, back: { color: "#4aa488", fontSize: 16 }, title: { color: "#263c36", fontSize: 19, fontWeight: "700" }, search: { paddingHorizontal: 20, paddingBottom: 12 }, input: { backgroundColor: "#f2f7f3", borderRadius: 14, padding: 14, fontSize: 16, color: "#263c36" }, filters: { flexDirection: "row", gap: 8, marginTop: 10 }, filter: { flex: 1, alignItems: "center", padding: 9, borderRadius: 10, backgroundColor: "#f2f7f3" }, filterActive: { backgroundColor: "#bfe5d6" }, filterText: { color: "#789087" }, filterTextActive: { color: "#267b63", fontWeight: "700" }, custom: { flexDirection: "row", gap: 8, marginTop: 8 }, customInput: { flex: 1, padding: 10, borderRadius: 10, backgroundColor: "#f2f7f3", color: "#263c36", fontSize: 12 }, scroll: { padding: 20 }, empty: { textAlign: "center", color: "#9aac9f", marginTop: 60 } });
