import { useState } from "react";
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import type { SchoolMilestone } from "@/services/calendar/schoolMilestone";

export function SchoolMilestonePrompt({ milestone, onLater, onSave }: { milestone: SchoolMilestone; onLater: () => void; onSave: (date: string) => Promise<void> }) {
  const [date, setDate] = useState(milestone.date); const [saving, setSaving] = useState(false);
  async function save() { const target = new Date(`${date}T00:00:00`); if (Number.isNaN(target.getTime()) || !/^\d{4}-\d{2}-\d{2}$/.test(date)) { Alert.alert("请输入有效日期", "格式：YYYY-MM-DD"); return; } setSaving(true); await onSave(date); setSaving(false); }
  return <Modal visible transparent animationType="fade"><View style={styles.backdrop}><View style={styles.card}><Text style={styles.title}>补充校历节点</Text><Text style={styles.message}>当前缺少“{milestone.label}”，请确认日期。保存后会作为校历记录，不会在当天发送通知。</Text><Text style={styles.year}>目标年份：{date.slice(0, 4)}</Text><TextInput value={date} onChangeText={setDate} style={styles.input} keyboardType="numbers-and-punctuation" placeholder="YYYY-MM-DD" /><View style={styles.actions}><Pressable onPress={onLater}><Text style={styles.later}>稍后</Text></Pressable><Pressable disabled={saving} onPress={save} style={styles.save}><Text style={styles.saveText}>{saving ? "保存中…" : "保存日期"}</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: "center", padding: 24, backgroundColor: "rgba(35,57,51,.28)" }, card: { padding: 22, borderRadius: 24, backgroundColor: "#fffdf8" }, title: { color: "#263c36", fontSize: 21, fontWeight: "700" }, message: { color: "#60766c", lineHeight: 22, marginTop: 12 }, year: { color: "#9aac9f", fontSize: 13, marginTop: 18 }, input: { marginTop: 8, padding: 14, borderRadius: 14, backgroundColor: "#f2f7f3", color: "#263c36", fontSize: 17 }, actions: { flexDirection: "row", justifyContent: "flex-end", alignItems: "center", gap: 18, marginTop: 20 }, later: { color: "#8ca198", fontSize: 16 }, save: { paddingHorizontal: 16, paddingVertical: 11, borderRadius: 14, backgroundColor: "#bfe5d6" }, saveText: { color: "#267b63", fontWeight: "700" } });
